Nbo/run duration monitoring
Cosmo-Tech/azure-sample-webapp pull request #261
Opened 2022-02-15 08:32 UTC by nborde-CSM

Dev Review rules:
- 3 PR max
- at the second feedback, prefer meet instead of github conversation

Definition of Done:
- [ ] Testing
- [ ] No error logs in web console (except iFrame errors)
- [ ] Create or Update documentation (README file for users/integrators)
- [ ] Check the [test page](https://spaceport.cosmotech.com/confluence/pages/viewpage.action?spaceKey=QA&title=Azure+Sample+Webapp) in order to manually validate the feature 
- [ ] Clean code (regroup configuration variable, typos, no console.log...)

2022-02-15 08:55 UTC, COSMO-EMI requested changes
Est-ce que tu as testé ce qui se passe dans les cas suivants :
- Lancer une simulation, fermer l'onglet, rouvrir l'onglet avant la fin de la simulation.
- Lancer une simulation, fermer l'onglet, rouvrir l'onglet après la fin de la simulation.

2022-02-15 08:55 UTC, COSMO-EMI commented on src/state/sagas/scenario/PollScenarioState/PollScenarioState.js
> +          const runDuration = Math.abs((runFinishTime - action.startTime) / 1000);
Le `Math.abs()` n'a pas d'utilité ici, si on lance `getTime()` régulièrement, on obtient une fonction strictement croissante.

En revanche, il manque peut-être des checks pour vérifier que `action.startTime` a une vraie valeur, histoire de ne pas enregistrer de résultat aberrant.

2022-02-15 14:36 UTC, nborde-CSM commented on src/state/sagas/scenario/PollScenarioState/PollScenarioState.js
> +          const runDuration = Math.abs((runFinishTime - action.startTime) / 1000);
Ok pour la fonction Abs. Le seul cas, où on pourrait avoir un temps négatif, c'est si quelqu'un réglait sa machine sur une date avant 1970.

Avec : 
`if (action.startTime != null)`
on s'assure qu'on n'a ni null ni undefined. J'ai pas en tête d'autres possibilités de valeur incohérente pour startTime.

2022-02-16 08:53 UTC, jreynard-code requested changes
Little changes but LGTM ;)

2022-02-16 08:53 UTC, jreynard-code commented on src/state/sagas/scenario/LaunchScenario/LaunchScenario.js
> +      scenario: { state: SCENARIO_RUN_STATE.RUNNING, startTime: runStartTime },
You do not use the startTime after setting it here. You can remove it

2022-02-16 08:53 UTC, jreynard-code commented on src/state/sagas/scenario/PollScenarioState/PollScenarioState.js
> +        if (action.startTime != null) {
Could be interesting to change the condition by `( action.startTime )` to manage truthy values.
See https://stackoverflow.com/questions/5515310/is-there-a-standard-function-to-check-for-null-undefined-or-blank-variables-in

2022-02-16 13:01 UTC, merged