Nbo/make scenario prameters more accessible
Cosmo-Tech/azure-sample-webapp pull request #263
Opened 2022-02-23 16:30 UTC by nborde-CSM

Dev Review rules:
- 3 PR max
- at the second feedback, prefer meet instead of github conversation

Definition of Done:
- [ ] Testing
- [ ] No error logs in web console (except iFrame errors)
- [ ] Create or Update documentation (README file for users/integrators)
- [ ] Check the [test page](https://spaceport.cosmotech.com/confluence/pages/viewpage.action?spaceKey=QA&title=Azure+Sample+Webapp) in order to manually validate the feature 
- [ ] Clean code (regroup configuration variable, typos, no console.log...)

2022-02-24 15:22 UTC, csm-thu requested changes

2022-02-24 15:22 UTC, csm-thu commented on src/components/ScenarioParameters/ScenarioParameters.js
> +  );
Could you move the `useState` declaration upward, near the top of the component declaration, to be next to the other `useState`s ?

2022-02-24 16:06 UTC, nborde-CSM commented on cypress/commons/actions/generic/Scenarios.js
> -}
I thought I removed it...

2022-02-24 16:13 UTC, nborde-CSM commented on src/views/Scenario/Scenario.js
> +        <Card style={{ height: '400px' }}>
It's an old miss...

2022-02-24 16:14 UTC, nborde-CSM commented on src/components/ScenarioParameters/ScenarioParameters.js
> +    flexDirection: 'row-reverse',
row-reverse is required to set expand/collapse icon on the right side of the accordion summary

2022-02-24 16:57 UTC, nborde-CSM commented on cypress/commons/actions/generic/Scenarios.js
> -}
scenario.parameters.tabs is still used with ScenarioParameters
It was just the same function.

2022-02-25 11:18 UTC, csm-thu approved these changes
LGTM :+1:

2022-02-25 11:43 UTC, merged