Vmi/filtering scenario name prod 7590
Cosmo-Tech/azure-sample-webapp pull request #43
Opened 2021-05-26 14:28 UTC by COSMO-VMI

2021-05-27 12:38 UTC, csm-thu requested changes

2021-05-27 12:38 UTC, csm-thu commented on public/locales/en/translation.json
> +                "forbiddenchars": "Scenario name has to starts with a letter, and can only contains letters, digits, spaces, underscores and hyphens."
Small typos: no 's' in "starts" and "contains"
"Scenario name has to start with a letter, and can only contain letters, digits, spaces, underscores and hyphens"

2021-05-27 12:38 UTC, csm-thu commented on src/components/CreateScenarioDialog/CreateScenarioDialog.js
> +                  {t(CREATE_SCENARIO_DIALOG_TITLE_LABEL_KEY)}
Could you add a default label ? (this will be useful if translations are missing for some languages)

2021-05-28 06:55 UTC, jreynard-code requested changes
LGTM, just little changes

2021-05-28 06:55 UTC, jreynard-code commented on src/views/Dashboards/README.md
> +/Scenario_x0020_Name%20eq%20%27<ScenarioName>%27
Could you please provide an example with <ScenarioId>?

2021-05-28 07:45 UTC, Nikeleos commented on src/components/CreateScenarioDialog/CreateScenarioDialog.js
> +      if (newScenarioName.match(/^\w[\w\d\s-]*$/) === null) {
If it's not reused, it should not be set in a constant.

2021-06-03 13:48 UTC, merged