Add a BasicDateInput in ScenarioParameters
Cosmo-Tech/azure-sample-webapp pull request #54
Opened 2021-05-31 09:14 UTC by COSMO-VMI

2021-05-31 13:35 UTC, csm-thu approved these changes
LGTM

2021-06-01 08:54 UTC, jreynard-code requested changes
LGTM, just little changes

2021-06-01 08:54 UTC, jreynard-code commented on src/components/ScenarioParameters/components/BasicTypes.js
> +    id: 'standard-required',
Could you please change the id and ids above, they sould be unique?

2021-06-01 08:54 UTC, jreynard-code commented on src/components/ScenarioParameters/components/BasicTypes.js
> +          label='Pick a date'
Could you please use 'useTranslation' hook here and above to change label regarding language?

2021-06-01 10:00 UTC, merged